

name: CI

on: [push]

jobs:
  # This job will:
  #   * deploy a draft every time there is a commit that is not on master branch
  #   * comment on that commit with the deploy URL
  deployCommitDraft:
    name: Deploy draft to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref != 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.17.0

      - name: Install yarn
        run: npm install -g yarn

      - name: Use cache for yarn if available
        uses: c-hive/gha-yarn-cache@v1

      - name: Install yarn dependencies
        run: yarn install

      - name: Build website
        run: yarn build

      # ... your other build steps to produce a build directory
      # e.g. `npm run build` for create-react-app

      - name: Deploy draft to Netlify
        id: netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './public'
          draft: true
          comment-on-commit: true

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Start crusher tests
        run: |
          curl --location --request POST 'https://backend.crusher.dev/projects/1054/tests/actions/run' \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --cookie "token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDg5IiwidGVhbV9pZCI6NDE0LCJpYXQiOjE2NDU0MDg4NjEsImV4cCI6MTY3Njk0NDg2MX0.TO6TgdEOOkM_N05B_YrogMOvvdpzOBpIADdbPaZ-d6U" \
          --data-urlencode 'githubRepoName=himanshu-dixit/personal-gatsby-website' \
          --data-urlencode 'host=${{steps.netlify.outputs.preview-url}}' \
          --data-urlencode 'githubCommitId=${{ steps.vars.outputs.sha_short}}'

  # This job will:
  #   * deploy a production build every time there is a push only on the master branch
  #   * comment that commit with the deploy URL
  publishMasterCommit:
    name: Publish to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      # ... your other build steps to produce a build directory
      # e.g. `npm run build` for create-react-app
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.17.0

      - name: Install yarn
        run: npm install -g yarn

      - name: Use cache for yarn if available
        uses: c-hive/gha-yarn-cache@v1

      - name: Install yarn dependencies
        run: yarn install

      - name: Build website
        run: yarn build

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './public'
          comment-on-commit: true
