# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Run crusher test

on:
  deployment_status


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get deployment URL
        id: deployment
        uses: dorshinar/get-deployment-url@master
        timeout-minutes: 5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run end-to-end tests
        run: npm run test:e2e
        env:
          deployment: ${{ steps.deployment.outputs.deployment }}
