on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: himanshu-dixit/prettier-putout@v1.1.4
        with:
          who-to-greet: 'Mona the Octocat'
