on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: putout-prettier
        uses: himanshu-dixit/prettier-putout@v1.1.8
        with:
          putoutDir: 'src'
          pretteirDir: 'src'
      - name: Setup tmate session
        if: success() || failure()
        uses: mxschmitt/action-tmate@v3
